### ISSUE TITLE
Enable to configure the delay between servers polling  

### ISSUE THREAD

**Issue by avankemp** [kgiusti/ombt#26]
We noted that in some experiments (rpc-cast for example) with a lot of messages sent, not all the messages were received from the servers perspective. We suspect that it's because the controller does not wait long enough before exiting the test.

For now, the `--delay`parameter passed in a 'rpc-cast' experiment is used to wait for the messages to propagate  https://github.com/kgiusti/ombt/blob/243876f79a8b9acb6b664343d4316e2441c96e40/ombt2#L896

But the delay between servers pollings used in the `_query_servers` function is based on the parameter `pause`, not `delay` (actually `pause * 2`) https://github.com/kgiusti/ombt/blob/243876f79a8b9acb6b664343d4316e2441c96e40/ombt2#L898

It could be great to pass here the delay in order to make this time configurable. 

Actually, we tried on some failing tests with a much larger delay value, and all the messages were then correctly received at the end of them :) I can PR it, if that makes sense to you!

**Comment by kgiusti** [comment]
The pause  passed to _query_servers sets the poll rate for the query loop.  The reason it is set to 2x the transmit pause interval is to prevent the loop from polling faster than a client sends messages. Usually pause will be zero or pretty small since usually we want the clients to put load on the message bus.  But we don't want to poll that fast so we put a lower bounds on the poll rate if there is no pause.

'delay' is a one time pause between the last message transmitted from a client and the first poll of the servers to compensate for propagation delay.  As such a good value of delay would be worse case latency between client and server x 2.  That latency can be obtained by running a few tests with a really huge delay and examining the resulting metrics.

So we're trying to factor two constraints: propagation delay (via delay) and transmit interval (via pause).  The former prevents the controller from starting the poll too soon, and the latter ensures that it polls no faster than the expected incoming arrival rate.

Instead of adding a dedicated parameter for poll rate I think we can solve the issue you're seeing by fixing the heuristic used by _query_servers to determine when the test is done.

_query_servers knows how many messages are expected at the servers.  There's also a global test timeout parameter (--timeout) that can be passed to the controller.  I'd like to refactor the query code to use that timeout instead of guessing when the traffic is done by counting the polls resulting in zero messages.

Let me try this out and if it seems to work for me I'll post a PR for you to try.

**Comment by msimonin** [comment]
Just tested  6ac8255, here are the results : 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/2486813/34953290-bd2d978c-fa1c-11e7-8f4a-1f8a1663fa54.png">

Note that timeout was set to 8000.

So, it seems that `ombt` is now getting the right amount of message (`server_ok + server_fail` and `client_ok + client_fail`).
From my side this fixes the issue. Thanks @kgiusti !

For the record here is the distribution for the 1/16/cast case (interesting to see how the distribution is "shifted to the right") : 
```
 '_agg_servers': {'errors': {},
  'latency': {'count': 200000,
   'distribution': {'0': [0, 0, 2, 2, 2, 1, 1, 2, 2, 2],
    '1': [0, 17, 16, 14, 0, 0, 0, 0, 0, 0],
    '4': [0, 0, 203, 27937, 53572, 31460, 29218, 28418, 29131, 0]},
   'max': 89224.75695610046,
   'min': 2.051115036010742,
   'sum_of_squares': 731303228062445.5,
   'total': 11620988001.95837},
```
